name: Build and Deploy JavaDoc

on:
  push:
    branches:
      - master
      - cucumber-examples

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Build Test Javadocs
        run: mvn -B javadoc:test-javadoc

      - name: Generate Site
        run: mvn -B site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_1 }}
          publish_dir: |
            ./target/site/main-javadoc
            ./target/site/test-javadoc
            ./target/site/