name: Build and Deploy JavaDoc, and Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if 'NoDeploy' keyword is present in commit message
        run: |
          if [[ ${{ github.event.head_commit.message}} == *'NoDeploy'* ]]; then
            echo "NoDeploy keyword found in the commit message. Exiting workflow."
            exit 78  # Exit with a neutral status code (78) to indicate skipping the workflow.
          fi
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Generate JavaDoc and site
        run: |
          mvn -B javadoc:javadoc
          mvn -B javadoc:test-javadoc
          mvn -B site

      - name: Rename folder and Modify Specific HTML
        run: |
          mv ./target/site/apidocs ./target/site/BDD-Framework
          mv ./target/site/testapidocs ./target/site/NBA-Project
          sed -i '/<td style="text-align: left;">Homepage<\/td>/a <td style="text-align: left;"><a href='\''./BDD-Framework/index.html'\''>BDD Framework</a><br><a href='\''./NBA-Project/index.html'\''>NBA Test Project</a></td>' ./target/site/summary.html
          sed -i 's/Assignment \(.*\) API/BDD-Framework \1/' ./target/site/BDD-Framework/index.html
          sed -i 's/Assignment \(.*\) Test API/NBA-Project \1/' ./target/site/NBA-Project/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_1 }}
          publish_dir: ./target/site/