name: Build and Deploy JavaDoc, and Site

on:
  push:
    branches:
      - cucumber-examples

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Build Test Javadocs
        run: mvn -B javadoc:test-javadoc

      - name: Generate Site
        run: mvn -B site

      - name: Rename Folders
        run: |
          mv ./target/site/apidocs ./target/site/BDD-Framework
          mv ./target/site/testapidocs ./target/site/NBA-Project

      - name: Modify Specific HTML
        run: |
          sed -i '/<td style="text-align: left;">Homepage<\/td>/a <td style="text-align: left;"><a href='\''./BDD-Framework/index.html'\''>BDD Framework</a><br><a href='\''./NBA-Project/index.html'\''>NBA Test Project</a></td>' ./target/site/summary.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_1 }}
          publish_dir: ./target/site/
