name: Build and Deploy JavaDoc, and Site

on:
  push:
    branches:
      - cucumber-examples

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Build Test Javadocs
        run: mvn -B javadoc:test-javadoc

      - name: Generate Site
        run: mvn -B site

      - name: Print before summary.html
        run: cat ./target/site/summary.html

      - name: Modify Specific HTML
        run: |
          sed -i '/<td style="text-align: left;">Homepage<\/td>/a <td style="text-align: left;"><a href='\''./apidocs/index.html'\''>Main Documentation</a><br><a href='\''./testapidocs/index.html'\''>Test Documentation</a></td>' ./target/site/summary.html

      - name: Print after summary.html
        run: cat ./target/site/summary.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_1 }}
          publish_dir: ./target/site/
