name: Build and Deploy JavaDoc, and Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if 'DontDeploy' keyword is present in commit message
        id: check_commit_message
        run: |
          # Check if the commit message contains 'DontDeploy'
          if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == *'DontDeploy'* ]]; then
            echo "Commit message contains 'NoDeploy'. Skipping the workflow."
            echo "::set-output name=skip_workflow::true"
          fi  

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        if: steps.check_commit_message.outputs.skip_workflow != 'true'
        with:
          java-version: 21

      - name: Generate JavaDoc and site
        if: steps.check_commit_message.outputs.skip_workflow != 'true'
        run: |
          mvn -B javadoc:javadoc
          mvn -B javadoc:test-javadoc
          mvn -B site

      - name: Rename folder and Modify Specific HTML
        if: steps.check_commit_message.outputs.skip_workflow != 'true'
        run: |
          mv ./target/site/apidocs ./target/site/BDD-Framework
          mv ./target/site/testapidocs ./target/site/NBA-Project
          sed -i '/<td style="text-align: left;">Homepage<\/td>/a <td style="text-align: left;"><a href='\''./BDD-Framework/index.html'\''>BDD Framework</a><br><a href='\''./NBA-Project/index.html'\''>NBA Test Project</a></td>' ./target/site/summary.html
          sed -i 's/Assignment \(.*\) API/BDD-Framework \1/' ./target/site/BDD-Framework/index.html
          sed -i 's/Assignment \(.*\) Test API/NBA-Project \1/' ./target/site/NBA-Project/index.html

      - name: Deploy to GitHub Pages
        if: steps.check_commit_message.outputs.skip_workflow != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_1 }}
          publish_dir: ./target/site/